### ISSUE TITLE
GLib-GObject-CRITICAL

### ISSUE THREAD

**Issue by s1rleblanc** [wernerturing/multi-delogo#7]
hi everyone i just compile again multi-delogo im on MacOS Mojave and run it it show this:

$ ./multi-delogo 
objc[32990]: Class GNotificationCenterDelegate is implemented in both /usr/local/opt/glib/lib/libgio-2.0.0.dylib (0x1088b5588) and /opt/local/lib/libgio-2.0.0.dylib (0x110323498). One of the two will be used. Which one is undefined.

(process:32990): Gtk-WARNING **: 15:29:45.037: Locale not supported by C library.
	Using the fallback 'C' locale.
dbus[32990]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!

(process:32990): GLib-GObject-CRITICAL **: 15:29:51.036: g_object_set_qdata_full: assertion 'quark > 0' failed
Segmentation fault: 11

before i recompile it.. it doesn't do that.. any help ?

**Comment by wernerturing** [comment]
Sorry about the delay.

I'm not sure if this is still relevant, but the line

objc[32990]: Class GNotificationCenterDelegate is implemented in both /usr/local/opt/glib/lib/libgio-2.0.0.dylib (0x1088b5588) and /opt/local/lib/libgio-2.0.0.dylib (0x110323498). One of the two will be used. Which one is undefined.

indicates that there are two installations of glib, one in /usr/local/opt and one in /opt/local. Unfortunately I don't know where they came from, and neither looks like a path used by Homebrew (but I could be wrong about that).

You'd need to fix your setup so that only one copy of the libraries is found.
